{
 "title": "dashboard-example",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Aviatrix Field Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tunnels - Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(tunnel) (status) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnels - Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by(tunnel) (status) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(gateway) (status) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by(gateway) (status) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - Packet Drop Rate",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gateway) (rate_pkt_drop)",
     "legendFormat": "{{gateway}}"
    }
   ]
  },
  {
   "title": "Controller - CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_us{gateway=\"Controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_us", "legendFormat": "{{gateway}}" }
   ]
  },
  {
   "title": "All Gateways - Total Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate_total{gateway!=\"Controller\"}",
     "legendFormat": "{{gateway}}"
    }
   ]
  }
 ]
}