{
 "title": "status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gateways - Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(gateway) (status) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by(gateway) (status) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnels - Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(tunnel) (status) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tunnels - Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(sum by(tunnel) (status) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Peer 10.40.251.1 (Equinix)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bgp_status{bgp_neighbor=\"sv-metro-equinix-demo-edge-1-to-sv-metro-equinix-demo-host-vm-1(10.40.251.1)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateways - CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_us", "legendFormat": "{{gateway}}" }
   ]
  },
  {
   "title": "Gateways - Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 20, "w": 10, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ((memory_available - memory_free) / memory_available) * 100",
     "legendFormat": "{{gateway}}"
    },
    {}
   ]
  },
  {
   "title": "Gateway Status",
   "type": "stat",
   "gridPos": { "h": 20, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "status{gateway!=\"\"}",
     "legendFormat": "{{gateway}}"
    }
   ]
  }
 ]
}