{
 "title": "traffic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>US-East-1</h1></center>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "<center><h1>US-East-2</h1></center>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<center><h1>North Europe</h1></center>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "<center><h1>US West 1</h1></center>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-aws-us-east-1\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_sent{gateway=\"transit-aws-us-east-1\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-aws-us-east-2\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_sent{gateway=\"transit-aws-us-east-2\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-azure-north-europe\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_sent{gateway=\"transit-azure-north-europe\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-gcp-us-west1\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_sent{gateway=\"transit-gcp-us-west1\"})/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-aws-us-east-1\"})/1024",
     "legendFormat": "US East 1 - RX"
    },
    {
     "expr": "sum(rate_sent{gateway=\"transit-aws-us-east-1\"})/1024",
     "legendFormat": "US East 1 - TX"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-aws-us-east-2\"})/1024",
     "legendFormat": "US East 2 - RX"
    },
    {
     "expr": "sum(rate_sent{gateway=\"transit-aws-us-east-2\"})/1024",
     "legendFormat": "US East 2 - TX"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-azure-north-europe\"})/1024",
     "legendFormat": "North Europe- RX"
    },
    {
     "expr": "sum(rate_sent{gateway=\"transit-azure-north-europe\"})/1024",
     "legendFormat": "North Europe - TX"
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate_received{gateway=\"transit-gcp-us-west1\"})/1024",
     "legendFormat": "US West 1 - RX"
    },
    {
     "expr": "sum(rate_sent{gateway=\"transit-gcp-us-west1\"})/1024",
     "legendFormat": "US West 1 - TX"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate_rx_drop{gateway=\"transit-aws-us-east-1\"})",
     "legendFormat": "US East 1 - RX"
    },
    {
     "expr": "sum(rate_tx_drop{gateway=\"transit-aws-us-east-1\"})",
     "legendFormat": "US East 1 - TX"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate_rx_drop{gateway=\"transit-aws-us-east-2\"})",
     "legendFormat": "US East 2 - RX"
    },
    {
     "expr": "sum(rate_tx_drop{gateway=\"transit-aws-us-east-2\"})",
     "legendFormat": "US East 2 - TX"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate_rx_drop{gateway=\"transit-azure-north-europe\"})",
     "legendFormat": "North Europe - RX"
    },
    {
     "expr": "sum(rate_tx_drop{gateway=\"transit-azure-north-europe\"})",
     "legendFormat": "North Europe - TX"
    }
   ]
  },
  {
   "title": "Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate_rx_drop{gateway=\"transit-gcp-us-west1\"})",
     "legendFormat": "US West 1 - RX"
    },
    {
     "expr": "sum(rate_tx_drop{gateway=\"transit-gcp-us-west1\"})",
     "legendFormat": "US West 1 - TX"
    }
   ]
  },
  {
   "title": "Gateways - PPS Limit Exceeded",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gateway) (pps_limit_exceeded)",
     "legendFormat": "{{gateway}}"
    }
   ]
  },
  {
   "title": "Gateways - BW Limit Exceeded",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gateway) (bandwidth_ingress_limit_exceeded)",
     "legendFormat": "{{gateway}}"
    }
   ]
  }
 ]
}